provider:
  name: faas
  gateway: http://localhost:8080
functions:
  current--datetime-csharp:
    lang: csharp
    handler:  # empty if stack.yml in the same localization
    image: faas-current-datetime-csharp